### ISSUE TITLE
write() doesn't recognise shifted characters

### ISSUE THREAD

**Issue by EvilDragonfiend** [ReggX/pydirectinput_rgx#4]
write() doesn't recognise shifted characters.
if you need to write `ABCD` or `!@#$`, you're supposed to make your own def with like:

```python3
def key_write(text, delay=default_delay):
    for each in text:
        key_press_for_write(each, timer=0.02, delay=0)
    time.sleep(delay)

def key_press_for_write(key, timer=0.1, delay=default_delay):
    shift_flag = False
    if key in "~!@#$%^&*()_+" or string.isupper(key):
        shift_flag = True
    if shift_flag:
        hold_shift(0)
    key_down(key, 0)
    time.sleep(timer)
    key_up(key, 0)
    if shift_flag:
        unhold_shift(0)
    time.sleep(delay)
```
(some methods are customised for my personal uses, but I am sure you can recognise what these are for)

**Comment by EvilDragonfiend** [comment]
oh, wait, it's written in the original docu that it doesn't support those lol. nvm then

**Comment by ReggX** [comment]
This fork supports automatic shifting, but it has to be explicitly enabled, `typewrite(message, auto_shift=True)` 
See https://github.com/ReggX/pydirectinput_rgx/blob/rgx_v2.0.6/pydirectinput/__init__.py#L3705

If your target application supports WM_UNICHAR messages (like text editors, less likely for games, but it's best to just test if your desired target supports it), then it's preferable to use `unicode_typewrite(message)` 
See https://github.com/ReggX/pydirectinput_rgx/blob/rgx_v2.0.6/pydirectinput/__init__.py#L4070

I'm still keeping this issue closed since the desired feature already exists.
