### ISSUE TITLE
 send key to a specified background window?

### ISSUE THREAD

**Issue by x2nbit** [ReggX/pydirectinput_rgx#8]
Thank you for sharing this helpful library! It’s very useful for sending key to an active window in various ways.

However, sometimes there's a need to send key to a window that is not active. The window is not minimized; it's just not the currently active window. Is there any way to send key to a specified background window?

**Comment by ReggX** [comment]
Hi,

I hate to be the bearer of bad news, but unfortunately, the Windows API function that this library is using (SendInput), only supports injecting input into the foreground thread.

While there might be a way to use PostMessage to send WM_KEYDOWN and WM_KEYUP messages to any thread, their compatibility is very limited. See also:

https://stackoverflow.com/questions/73161057/posting-a-wm-keydown-message-without-the-following-wm-char-message-for-automatin
https://devblogs.microsoft.com/oldnewthing/20050530-11/?p=35513

Since this library was created with compatibility in mind, adding a new way to send some limited input to some limited applications, is unfortunately not in scope of the project. As such, there are no plans to implement those API calls at this time. 😞

**Comment by x2nbit** [comment]
Thank you very much for your reply and letting me know more details, indeed as you said, PostMessage is not a perfect solution at the moment 😥.
But that doesn't stop the library from being very useful,thanks again for the code! 😊
